# docker-compose.yml (The Ultimate Final Version)
version: '3.8'

services:
  airflow:
    # This tells Docker to build the image from the Dockerfile in this directory
    build: .
    container_name: airflow_final
    environment:
      # Airflow Core Configuration (uses SQLite)
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      
      # This is for YOUR custom script to use
      - DATABASE_URL=postgresql+psycopg2://stocks:stocks_pw@host.docker.internal:5432/stockdb
      - ALPHAVANTAGE_API_KEY=RB68472YOIWU13JK
      - SYMBOLS=AAPL,MSFT,GOGL
      - SCHEDULE_CRON=0 * * * *

    volumes:
      # Mount the dags folder (which now contains the scripts folder)
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - airflow-db:/opt/airflow/
    ports:
      - "8081:8080"
    command: standalone
    restart: always

volumes:
  airflow-db: