# docker-compose.yml (Final Version with Hardcoded Variables)
version: '3'

x-airflow-common: &airflow-common
  image: apache/airflow:2.7.1
  environment:
    - DATABASE_URL=postgresql+psycopg2://stocks:stocks_pw@host.docker.internal:5432/stockdb
    - AIRFLOW__CORE__FERNET_KEY=o38iBsMkw7c3SBeJlwJwN8BX0sBS8LhgtdiWEFFoPCc=
    - ALPHAVANTAGE_API_KEY=RB68472YOIWU13JK
    - SYMBOLS=AAPL,MSFT,GOOGL
    - SCHEDULE_CRON=0 * * * *
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
    - ./logs:/opt/airflow/logs

services:
  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8081:8080"
    depends_on:
      - airflow-init
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    depends_on:
      - airflow-init
    restart: always